export const ENVIRONMENTAL_VARIABLES = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION: 'JWT_EXPIRATION',
  JWT_REFRESH_EXPIRATION: 'JWT_REFRESH_EXPIRATION',
  ENCRYPTION_KEY: 'ENCRYPTION_KEY',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  // Cloudflare R2 / S3-compatible storage
  R2_BUCKET_NAME: 'R2_BUCKET_NAME',
  R2_PUBLIC_URL: 'R2_PUBLIC_URL',
  R2_ENDPOINT: 'R2_ENDPOINT',
  R2_ACCESS_KEY_ID: 'R2_ACCESS_KEY_ID',
  R2_SECRET_ACCESS_KEY: 'R2_SECRET_ACCESS_KEY',
  // Email (Resend)
  RESEND_API_KEY: 'RESEND_API_KEY',
  RESEND_FROM_EMAIL: 'RESEND_FROM_EMAIL',
  // App URLs
  APP_URL: 'APP_URL',
} as const;
